steps:
  - label: "Deploy epic-collabs frontend"
    trigger: "epic-collabs-frontend-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        STAGE: "production"
