version: '3'
services:
  epic-collabs:
    build:
      context: ./backend/services/epic-collabs
      args:
        - NPM_TOKEN
  epic-collabs-frontend:
    build:
      context: ./frontend/epic-collabs-frontend
      args:
        - NPM_TOKEN
