service: epic-collabs-service
frameworkVersion: '>=1.21.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: ${cf:epic-collabs-service-stateful-${opt:stage}.LambdaExecutionRole}
  environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-logless-plugin
  - serverless-dynamodb-parameters
  - serverless-prune-plugin

custom:
  logless:
    logRetention: ${ddb:/${opt:stage}/epic-collabs/config/LOG_RETENTION_IN_DAYS}

  serverless-dynamodb-parameters:
    tableName: kloud-config-epic-collabs-service-${opt:stage}

package:
  exclude:
    - '*.sh'
    - .serverless/**
    - .build/**
    - .buildkite/**
    - bin/**
    - coverage/**
    - src/**/*.test.js
    - .editorconfig
    - .env-*
    - .tslint*
    - .envrc
    - .gitignore
    - .node-version
    - .yarnrc
    - package.json
    - yarn.lock
    - README.md
    - webpack.config.js
    - tsconfig.json
    - schema.graphql
    - __mocks__
    - __test__

functions:
  jwtAuthorizer:
    handler: src/functions/jwt-authorizer/index.handler
    memorySize: 512
    environment:
      STAGE: ${opt:stage}
    alarms:
      - name: functionInvocations
        threshold: 3000
    tags:
      FunctionType: authorizer

  auth0Login:
    handler: src/functions/auth0-login/index.handler
    memorySize: 512
    timeout: 20
    environment:
      STAGE: ${opt:stage}
    events:
      - http:
          path: auth0/login
          method: post
          private: true
    alarms:
      - name: functionInvocations
        threshold: 3000
    tags:
      FunctionType: webhook
      WebHookSource: auth0

  graphql:
    handler: src/gql/index.handler
    memorySize: 1536
    timeout: 20
    environment:
      STAGE: ${opt:stage}
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            maxAge: 86400
          authorizer:
            name: jwtAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    tags:
      FunctionType: graphql_api
