module.exports = {
  SSR_ENABLED: true,
  STAGE: process.env.STAGE,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_SECRET: process.env.AUTH0_SECRET,
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  SESSION_COOKIE_SECRET: process.env.SESSION_COOKIE_SECRET,
  BASE_URL: process.env.BASE_URL,
  AUTH0_REDIRECT_URL: process.env.AUTH0_REDIRECT_URL,
  AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
  GRAPHQL_ENDPOINT: process.env.GRAPHQL_ENDPOINT
};
