steps:
  - label: "Deploy"
    trigger: "epic-collabs-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        STAGE: "stevenp"
        ROLE_ARN: arn:aws:iam::160813253081:role/buildkite
