steps:
  - label: "Deploy"
    trigger: "epic-collabs-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        STAGE: "sp"
        ROLE_ARN: arn:aws:iam::315646104322:role/sp-buildkite
