steps:
  - label: Run PR
    command:
      - "yarn lint"
      - "yarn test"
    agents:
      queue: default
    plugins:
      docker-compose#v3.5.0:
        run: epic-collabs
        env:
          - NPM_TOKEN
