plugins:

  - removeDoctype
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: false
  - removeXMLNS: false
  - removeEditorsNSData: false
  - cleanupAttrs: false
  - inlineStyles: false
  - minifyStyles: false
  - convertStyleToAttrs: false
  - cleanupIDs: true
  - prefixIds: false
  - removeRasterImages: false
  - removeUselessDefs: false
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors: false
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill: false
  - removeViewBox: false
  - cleanupEnableBackground: false
  - removeHiddenElems: false
  - removeEmptyText: false
  - convertShapeToPath: false
  - convertEllipseToCircle: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: false
  - convertPathData: false
  - convertTransform: false
  - removeEmptyAttrs: false
  - removeEmptyContainers: false
  - mergePaths: false
  - removeUnusedNS: false
  - sortAttrs: false
  - sortDefsChildren: false
  - removeTitle: true
  - removeDesc: true
  - removeDimensions: false
  - removeAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: false
  - removeScriptElement: false
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: false
  - reusePaths: false
